### ISSUE TITLE
check this out for forms 

### ISSUE THREAD

**Issue by sain0136** [sain0136/rotary_club_devolpment#5]
https://www.youtube.com/watch?v=XZF71ij463Y
https://vueformulate.com/

**Comment by sain0136** [comment]
https://drive.google.com/drive/folders/1yjiNJk4i522ZKVHUKj7Wg1LN4tnLVoI8?usp=sharing
apo we for got to give you the usb stick but i copied all the resources in a google drive folder

**Comment by karkaplani** [comment]
That's cool man thanks
